name: Build images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v3

    - name: Import cache
      id: cache-src
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-build-${{ hashFiles('src/*/README.md') }}
        path: |
          ./src

    - name: Dependencies
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.11
      run: |
        brew install nasm acpica
    
    - name: Build
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.11
      run: |
        mkdir output
        make 
        make OpenCoreEFIFolder-master.zip
        make OpenCore-master.dmg
        mv OpenCoreEFIFolder-master.zip OpenCore-master.dmg output/
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: OpenCoreArtifacts
        path: output
